# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_more_info',
            name='sex',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.sex', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='users_more_info',
            name='xueli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.XueLi', verbose_name='学历'),
        ),
    ]
