# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file_information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=526, verbose_name='文件名称')),
                ('file_info', models.TextField(verbose_name='文件备注')),
                ('file_create_time', models.DateTimeField(auto_now_add=True, verbose_name='文件创建时间')),
                ('file_change_time', models.DateTimeField(auto_now=True, verbose_name='文件修改时间')),
                ('file', models.FileField(upload_to='static/work/doc/', verbose_name='文件')),
                ('file_status', models.IntegerField(default=1, verbose_name='当前状态')),
                ('over_time', models.CharField(default='', max_length=255, verbose_name='截至时间')),
                ('word_path', models.CharField(default='', max_length=256, verbose_name='导出word文件')),
                ('fanyi_zl', models.IntegerField(default=0, verbose_name='翻译种类')),
                ('yuan', models.IntegerField(default=0, verbose_name='源文语言种类')),
                ('mubiao', models.IntegerField(default=0, verbose_name='目标语言种类')),
                ('all_num', models.IntegerField(default=0, verbose_name='文章总字数')),
                ('numing', models.IntegerField(default=0, verbose_name='已修改的字数')),
                ('all_para', models.IntegerField(default=0, verbose_name='文章总段数')),
                ('paraing', models.IntegerField(default=0, verbose_name='已修改段数')),
                ('jindu', models.IntegerField(default=0, verbose_name='当前的进度')),
                ('work_count', models.IntegerField(default=0, verbose_name='文件被打开几次')),
                ('corpus_matching_count', models.IntegerField(default=0, verbose_name='语料库匹配数量')),
                ('paragraph_count', models.IntegerField(default=0, verbose_name='总段数，做预翻译进度使用')),
                ('pre_translation', models.CharField(default=0, max_length=23, verbose_name='当前预翻译的进度百度比')),
                ('file_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YiWenTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yiwen', models.TextField(verbose_name='译文句子')),
                ('yiwen_change', models.TextField(default=' ', verbose_name='译文修改句子')),
                ('yiwen_wait_over', models.TextField(default='', verbose_name='译文待人工编译')),
                ('yiwen_style', models.CharField(default='', max_length=256, verbose_name='译文标题样式')),
                ('style_value', models.CharField(default='', max_length=255, verbose_name='样式的值')),
                ('is_table', models.IntegerField(default=0, null=True, verbose_name='是否为表格')),
                ('table_style', models.CharField(max_length=66, null=True, verbose_name='表格的样式')),
                ('row', models.IntegerField(null=True, verbose_name='表格的行数')),
                ('img_path', models.CharField(default='', max_length=86, null=True, verbose_name='文档图片位置')),
                ('alignment', models.IntegerField(default=0, null=True, verbose_name='段落对齐样式')),
                ('yiwen_number', models.IntegerField(default=0, verbose_name='译文每句序号')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.file_information')),
            ],
        ),
        migrations.CreateModel(
            name='YuanWenTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yuanwen', models.TextField(verbose_name='原文句子')),
                ('yuanwen_change', models.TextField(default='', verbose_name='原文修改句子')),
                ('yuanwen_style', models.CharField(default='', max_length=256, verbose_name='原文标题样式')),
                ('style_value', models.CharField(default='', max_length=255, verbose_name='样式的值')),
                ('check_changeed', models.IntegerField(default=0, verbose_name='是否修改过')),
                ('is_table', models.IntegerField(default=0, null=True, verbose_name='是否为表格')),
                ('table_style', models.CharField(max_length=66, null=True, verbose_name='表格的样式')),
                ('row', models.IntegerField(null=True, verbose_name='表格的行数')),
                ('img_path', models.CharField(default='', max_length=86, null=True, verbose_name='文档图片位置')),
                ('alignment', models.IntegerField(default=0, null=True, verbose_name='段落对齐样式')),
                ('yuanwen_number', models.IntegerField(default=0, verbose_name='原文每句序号')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.file_information')),
                ('table_gl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.YuanWenTable', verbose_name='关联第一个单元格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='yiwentable',
            name='gl',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.YuanWenTable'),
        ),
        migrations.AddField(
            model_name='yiwentable',
            name='table_gl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='work.YiWenTable', verbose_name='关联第一个单元格'),
        ),
        migrations.AddField(
            model_name='yiwentable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
